### PR TITLE
Prepare for PNG icon removal from core

### PR DESCRIPTION
**Pull request by NotMyFault**
@MarkEWaite Preparation for https://github.com/jenkinsci/jenkins/pull/5778

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Review by MarkEWaite — COMMENTED** [review]
Doesn't this also need an increase in the Jenkins minimum version required by the plugin?

**Comment by NotMyFault** [comment]
> Doesn't this also need an increase in the Jenkins minimum version required by the plugin?

No, older versions of Jenkins pick the PNG icon, newer versions pick the SVG icon:

2.289.3:


2.323:

**Review by MarkEWaite — APPROVED** [review]
Thanks for the clarification.  Approved!

**Comment by MarkEWaite** [comment]
> @MarkEWaite Can we may get a release? The core PR is blocked until the plugin PRs are pulled and included in some release.

Thanks for the reminder @NotMyFault!  Included in https://github.com/jenkinsci/nodelabelparameter-plugin/releases/tag/nodelabelparameter-1.10.2

**Comment by NotMyFault** [comment]
> > @MarkEWaite Can we may get a release? The core PR is blocked until the plugin PRs are pulled and included in some release.
> 
> Thanks for the reminder @NotMyFault! Included in [1.10.2](https://github.com/jenkinsci/nodelabelparameter-plugin/releases/tag/nodelabelparameter-1.10.2)

No problem, thanks for the quick release 👍🏻

**Pull request merged**
