### PR TITLE
added test to increase test coverage for LabelParameterDefinition

### PR DESCRIPTION
**Pull request by sherlockbeard**
part of [JENKINS-69756 mprove node label parameter plugin automated test coverage](https://issues.jenkins.io/browse/JENKINS-69756)

### CODE REVIEW

**Comment by sherlockbeard** [comment]
How do I create StaplerRequest object and what value should be there to mock it ?

https://github.com/jenkinsci/nodelabelparameter-plugin/blob/00012dc037bf909fa0e72e380084e6e44f6de6a7/src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java#L253-L256

**Comment by MarkEWaite** [comment]
> How do I create StaplerRequest object and what value should be there to mock it ?
> 
> https://github.com/jenkinsci/nodelabelparameter-plugin/blob/00012dc037bf909fa0e72e380084e6e44f6de6a7/src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java#L253-L256

Don't attempt to create a mock of a stapler request.  Use a [JenkinsRule test](https://javadoc.jenkins.io/component/jenkins-test-harness/org/jvnet/hudson/test/JenkinsRule.html) to things that need Stapler.

**Review by MarkEWaite — APPROVED** [review]
Thanks very much!

**Comment by sherlockbeard** [comment]
> > How do I create StaplerRequest object and what value should be there to mock it ?
> > https://github.com/jenkinsci/nodelabelparameter-plugin/blob/00012dc037bf909fa0e72e380084e6e44f6de6a7/src/main/java/org/jvnet/jenkins/plugins/nodelabelparameter/NodeParameterDefinition.java#L253-L256
> 
> Don't attempt to create a mock of a stapler request. Use a [JenkinsRule test](https://javadoc.jenkins.io/component/jenkins-test-harness/org/jvnet/hudson/test/JenkinsRule.html) to things that need Stapler.

I found one example with mock . 

https://github.com/jenkinsci/custom-folder-icon-plugin/blob/2fe2b7118f7c15d39b75c77f9b6c70cfdfe6d6d3/src/test/java/jenkins/plugins/foldericon/utils/TestUtils.java#L68-L73

Is there any example with Jenkins rules? or which method to use to create request ?

**Pull request merged**
