### PR TITLE
[WiP] [JENKINS-22226] - NodeEligibility check violation should not lead to a permament build hanging

### PR DESCRIPTION
**Pull request by oleg-nenashev**
The behavior has been introduced in https://github.com/jenkinsci/nodelabelparameter-plugin/commit/c84f71466823c726420ab2f6af7dd989cf766bf7 and seems to be an "as designed", but actually the run cannot be restored if a node becomes online at some point.

### CODE REVIEW

**Comment by imod** [comment]
@oleg-nenashev will you do any further work on this?

**Comment by oleg-nenashev** [comment]
@imod Sorry, missed the comment. Will check the current status

**Comment by imod** [comment]
@oleg-nenashev from what I can tell, your test case does not fail

**Comment by oleg-nenashev** [comment]
Yeah. I have no memory of this place, so probably I should just unassign the issue and move the status back to "in progress"

**Comment by oleg-nenashev** [comment]
Sorry, I will unlikely have time to work on it anytime soon

**Pull request closed without merging**
