### PR TITLE
Improve test coverage of NodeLabelParameter

### PR DESCRIPTION
**Pull request by code-arnab**
### Testing done

Hello @MarkEWaite, Added some test case which improved the overall test coverage from 76% to 80%.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!  Approved.

I switched the `equals` and `hashCode` tests to use equalsverifier instead.  It performs a much deeper check of the equals implementation and the hashCode implementation and requires less code.

Used the same technique to test one other class that has an `equals` implementation in the class.  There is still one class that has an `equals` implementation that is not checked by equalsverifier.  My attempts to use equalsverifier on that class failed and I ran out of time to investigate further.

**Comment by code-arnab** [comment]
> Thanks! Approved.
> 
> I switched the `equals` and `hashCode` tests to use equalsverifier instead. It performs a much deeper check of the equals implementation and the hashCode implementation and requires less code.
> 
> Used the same technique to test one other class that has an `equals` implementation in the class. There is still one class that has an `equals` implementation that is not checked by equalsverifier. My attempts to use equalsverifier on that class failed and I ran out of time to investigate further.

Great! Thank You for switching to equalsverifier. I didn't know that there was already such a compact implementation is present. 
Maybe I can try to make the equalsverifier work on that failed class it will help me learn more about the equalsverfier.

**Comment by MarkEWaite** [comment]
> Maybe I can try to make the equalsverifier work on that failed class it will help me learn more about the equalsverfier.

You're welcome to do that.  It certainly is a way to learn and it will probably teach you many things about the relationship between the `equals` method, the `hashCode` method, and how those methods operate with Java inheritance.  It is also fine if you ignore it and call that an advanced topic for another time.

**Comment by code-arnab** [comment]
> > Maybe I can try to make the equalsverifier work on that failed class it will help me learn more about the equalsverfier.
> 
> You're welcome to do that.  It certainly is a way to learn and it will probably teach you many things about the relationship between the `equals` method, the `hashCode` method, and how those methods operate with Java inheritance.  It is also fine if you ignore it and call that an advanced topic for another time.

Sure 👍, if the implementation goes tangent to me I will move on to other issues.

**Pull request merged**
