### PR TITLE
Convert jquery to plain javascript

### PR DESCRIPTION
**Pull request by halkeye**
@MarkEWaite @uhafner 

I didn't actually test this, just did a lot of search and replace.

@MarkEWaite tested it from the Chrome debugger and from interactive testing and confirmed that the new code takes the same branches as the old code in all the cases that I tested.  I am unable to reach many of the branches in the code, even though I've clicked through the user interface in many different ways.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks so much @halkeye !  When I run the original code with Chrome developer tools enabled and set debugging breakpoints, I see that only very few branches of the Javascript are ever called based on the way that I'm using the plugin.  Those branches are related to disabling something, but I see no change in the UI based on the Javascript branches that are executed.

When I run your replacement with Chrome developer tools enabled and set debugging breakpoints, I only see a call to the outermost function, but none of the breakpoints that I set deeper in the code are ever reached.

I then ran a spot check by empty all content from the nodelabel.js file so that it was just an empty file.  When I run the user interface in that environment, I see no differences from the previous two cases.

I think that I'll need to explore the features of the plugin more deeply to understand how the Javascript is used and what it is actually doing.  Thanks again for taking the time to provide an implementation that does not use JQuery.

**Comment by halkeye** [comment]
> When I run your replacement with Chrome developer tools enabled and set debugging breakpoints, I only see a call to the outermost function, but none of the breakpoints that I set deeper in the code are ever reached.

fixed, i somehow deleted the () at the end of the IIFE

> I think that I'll need to explore the features of the plugin more deeply to understand how the Javascript is used and what it is actually doing. Thanks again for taking the time to provide an implementation that does not use JQuery.

Yea. I'm kinda confused about the logic of this script. I think its supposed to be showing/hiding based on other things that are selected, but not 100% following.

It should be working though. it at least runs, but i'm not certain its ported right.

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
My testing inside the Chrome debugger shows that I reach the same "disable" location(s) as I was able to reach with the previous code.  I was unable to reach other areas of the existing JQuery code or of the replacement pure Javascript code.  I'm prone to merge it so that we can remove the JQuery dependency from this plugin.

Any objections @halkeye ?

**Comment by halkeye** [comment]
i have no real stake in this. if your happy with it go ahead and merge.

**Pull request merged**
