### PR TITLE
[JENKINS-22185] Trigger a build in all nodes matching a label

### PR DESCRIPTION
**Pull request by amuniz**
[JENKINS-22185](https://issues.jenkins-ci.org/browse/JENKINS-22185)

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee: this plugin needs a coding style guide :dizzy_face:

**Comment by amuniz** [comment]
@recena agree. Let's do it in a separate PR and get this outstanding issue fixed first!

@reviewbybees done

**Comment by oleg-nenashev** [comment]
The fix looks good to me.
:bee:

**Comment by amuniz** [comment]
@imod do you think it is ok to merge?

**Comment by abayer** [comment]
fwiw, :bee:, and re-pinging @imod. =)

**Comment by imod** [comment]
sure, I'll take care of it

**Pull request merged**
