### PR TITLE
[JENKINS-33756] ensure nodes aren't scheduled more than once for execution

### PR DESCRIPTION
**Pull request by obataku**
potential fix for https://issues.jenkins.io/browse/JENKINS-33756

a non-concurrent job using nodelabelparameter-plugin will currently execute *twice* on the initial node if said node is also targeted by label

### CODE REVIEW

**Comment by obataku** [comment]
@MarkEWaite any clue what's up with these checks?

**Comment by obataku** [comment]
@MarkEWaite the new Jenkins check failure is opaque to me--can you make heads or tails of it?

**Comment by MarkEWaite** [comment]
> @MarkEWaite the new Jenkins check failure is opaque to me--can you make heads or tails of it?

We have to spread costs on the ci.jenkins.io agents by using AWS agents even though the controller is running on Azure.  That allows us to use AWS donated agents and CDF funded controller and storage.  Unfortunately, that also causes us to randomly receive agent disconnects.  The failure was due to an agent disconnect.  The simple workaround is to run the build again.  I've done that.

**Comment by obataku** [comment]
looks like another EC2 issue this time, @MarkEWaite; do you mind triggering another build? 🙂

**Review by MarkEWaite — APPROVED** [review]
I've tested many different ways and believe that this is doing the correct thing when it removes the initially scheduled node from the list of next nodes to be used.

**Pull request merged**
