### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by code-arnab**
### Testing done

Hello @MarkEWaite, added new test cases which improves the test coverage from 80% to 85%.
Thank You.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by code-arnab** [comment]
Thank You @MarkEWaite, for adding the latest changes.

**Comment by code-arnab** [comment]
@MarkEWaite I just noticed that the "equals" test for NextLabelCause has the class set to LabelParameterValue and the report says the coverage of equals is zero. I tried doing it but got some weird "Symmetry" problems. 
{25A323AB-CB97-4331-BB57-06B39FA28152}

**Comment by MarkEWaite** [comment]
> @MarkEWaite I just noticed that the "equals" test for NextLabelCause has the class set to LabelParameterValue and the report says the coverage of equals is zero. I tried doing it but got some weird "Symmetry" problems. {25A323AB-CB97-4331-BB57-06B39FA28152}

Thanks very, very much for detecting my mistake in that file!  You are absolutely right that the test of the equals contract in that file is testing the wrong class.  I'll need to look further into it.  Thanks again for catching that mistake!

**Comment by code-arnab** [comment]
> > @MarkEWaite I just noticed that the "equals" test for NextLabelCause has the class set to LabelParameterValue and the report says the coverage of equals is zero. I tried doing it but got some weird "Symmetry" problems. {25A323AB-CB97-4331-BB57-06B39FA28152}
> 
> Thanks very, very much for detecting my mistake in that file! You are absolutely right that the test of the equals contract in that file is testing the wrong class. I'll need to look further into it. Thanks again for catching that mistake!

Yup, no worries. Great Work!
This one surely is a bit tricky.

**Comment by MarkEWaite** [comment]
While reviewing your changes, I expanded the isEligible tests in d19126ea69f21724ce0a242693de015d8942d6d4 .  Let me know if any of those changes are an issue for you.

**Comment by code-arnab** [comment]
> While reviewing your changes, I expanded the isEligible tests in [d19126e](https://github.com/jenkinsci/nodelabelparameter-plugin/commit/d19126ea69f21724ce0a242693de015d8942d6d4) . Let me know if any of those changes are an issue for you.

No it looks great! If anything it has broaden my perspective of how good tests should be written and it also highlighted some nuances that I missed like wrong access modifiers and test cases. 
Though I had questions regarding the node setup that which I'd like to ask as I analyze it further.
Thank You again for the changes!

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by code-arnab** [comment]
> Thanks!

Thank You for the review!

**Pull request merged**
