### PR TITLE
test: getParameter Test case

### PR DESCRIPTION
**Pull request by Jagrutiti**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

I intend to complete the `getParameter` test case. I read about `AbstractBuild` and `TaskListener`.

My best guess is I have to assert the `labelExpanded` variable. 

But I was not sure how to initialize `AbstractBuild` and `TaskListener` in this method.

**Comment by MarkEWaite** [comment]
I think there are at least two alternatives.  

The most typical technique will test more deeply, but runs slower.  It involves using a JenkinsRule to define a job with a node parameter then run the job and get the resulting run as a build.  That path will let you explore many things about Jenkins objects as they are used in Jenkins core.  Look at src/test/java/org/jvnet/jenkins/plugins/nodelabelparameter/parameterizedtrigger/AllNodesForLabelBuildParameterFactoryTest.java for an example of that technique.

The less typical technique tests less deeply but runs faster.  It involves using mock objects to create the desired Java objects.  Refer to https://github.com/jenkinsci/embeddable-build-status-plugin/pull/117/files for an example of that technique that arrived during Hacktoberfest.

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Thanks for sharing the link to the test case. It helped me understand how to proceed. 

I found the class I am testing and the one you shared as a reference quite similar (feel free to correct me). Though their function is different.



From the `if` condition I understand that I have to check for a blank and non-blank string.

The [JenkinsRule documentation](https://javadoc.jenkins.io/component/jenkins-test-harness/org/jvnet/hudson/test/JenkinsRule.html) is huge. I made sure not to skip the methods invoked by JenkinsRules in `AllNodesForLabelBuildParameterFactoryTest`.

In `testLabelFactoryNonBlocking`, `createFreeStyleProject()` and `createSlaves()` methods are used.

I was confused about how do I decide which method I should use from JenkinsRule.

---

Though the following line in `getParameters()` in `AllNodesForLabelBuildParameterFactory` class:

`            labelExpanded = TokenMacro.expandAll(build, listener, labelExpanded);
`

and the below in  `getParameters()` in `NodeListBuildParameterFactory` class:

`            nodeListStringExpanded = TokenMacro.expandAll(build, listener, nodeListStringExpanded);
`

is common.

I did not understand how to test it.

**Comment by Jagrutiti** [comment]
Also,

I forgot to mention I am using the first technique. 

I do not have the expertise to mock. 

And would like to try `JenkinsRule`.

**Comment by MarkEWaite** [comment]
> Also,
> 
> I forgot to mention I am using the first technique.
> 
> I do not have the expertise to mock.
> 
> And would like to try `JenkinsRule`.

I won't be able to help until the end of this week at the earliest.  I'm traveling with family and visiting friends.

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Happy Holidays.

I would await your guidance when you're back.

**Comment by MarkEWaite** [comment]
Thanks.  I'm afraid that there are other reviews and improvements that are much higher on my list than this one.  It will likely be several more weeks before I'm able to look at this.  Sorry about that.

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Thank you for replying. 

I hope you will remember that I am waiting for your guidance when you are free from your priority work.

Or if you give me an estimation of when I can text you, I will ping you again.

**Comment by MarkEWaite** [comment]
Ping me again in two weeks

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Is this a good time to ping you again?

**Comment by MarkEWaite** [comment]
Thanks for the reminder.  It will be another week before I can help here.  There is a pull request on the git plugin that I need to test, merge, and release before I can help here.  See https://github.com/jenkinsci/git-plugin/pull/1305 for details

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Do you think I can lend you a hand with this release?

**Comment by MarkEWaite** [comment]
> Do you think I can lend you a hand with this release?

That's a great idea!  I need to test 

* https://github.com/jenkinsci/git-plugin/pull/1305

by duplicating [JENKINS-42971](https://issues.jenkins.io/browse/JENKINS-42971) while running the most recent release of the git plugin, then confirm that the issue is resolved after installing the [most recent plugin build (hpi file)](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-1305/lastBuild/)  from that pull request.  Once that is confirmed, I need some exploratory testing to confirm that the change did not harm any other functionality of the plugin.

Once I've completed that testing, I'll merge that pull request and release a new version of the git plugin.

Any help that you can give to those efforts would be greatly appreciated.

If you need a Docker container to help with that setup and want to experiment with docker, you could use [my docker-lfs branch lts-with-plugins](https://github.com/MarkEWaite/docker-lfs/blob/a369ad510781d31f716445d21f080828644b37ff/plugins.txt#L54) that already includes that git plugin version in its definition.

I also understand if you're not available to help with that.  Testing and releasing that plugin is my responsibility, but I'd love to have any help that you can offer.  Even if that help is "I installed the pre-release of the plugin and found no issues in my interactive testing".

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

I am available to help you with this :)

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

From the instructions and reading the issue, I understand that it is manual testing and I have to install the plugin (before and after release).

If you could share with me what I have to install from where, 
and a documentation with steps to install on Windows, it would be quite helpful.

I hope I am not increasing your task by asking for help. I am here to take some workload off you. 

If I am taking too much of your time I would understand if you do not want to guide me on this issue.

**Comment by Jagrutiti** [comment]
> If you checkout the `lts-with-plugins` branch locally, you should be able to run the command `docker_build.py` to build the container image that includes the plugins.

This helps. I will try it. Thanks.

**Comment by MarkEWaite** [comment]
That python script is unlikely to work on Windows.  I've wanted to develop the instructions for Windows anyway, so this is a good excuse to create instructions for Windows.  Will need some time so that I can finish current Jenkins and work meetings

**Comment by MarkEWaite** [comment]
Here is the batch file that does most of the same things that bash script does:

```
SET JENKINS_VERSION=2.361.4
SET JENKINS_WAR=..\jenkins-%JENKINS_VERSION%.war
IF NOT EXIST %JENKINS_WAR% (
   curl --location --output %JENKINS_WAR% https://get.jenkins.io/war-stable/%JENKINS_VERSION%/jenkins.war
)

IF NOT EXIST plugins (
    mkdir plugins
)

SET PLUGIN_MANAGER_VERSION=2.12.9
SET PLUGIN_MANAGER_FILE_NAME=jenkins-plugin-manager-%PLUGIN_MANAGER_VERSION%.jar
SET PLUGIN_MANAGER_JAR=..\%PLUGIN_MANAGER_FILE_NAME%

IF NOT EXIST %PLUGIN_MANAGER_JAR% (
   echo https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/%PLUGIN_MANAGER_VERSION%/%PLUGIN_MANAGER_FILE_NAME%
   curl --location --output %PLUGIN_MANAGER_JAR% https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/%PLUGIN_MANAGER_VERSION%/%PLUGIN_MANAGER_FILE_NAME%
)

java -jar %PLUGIN_MANAGER_JAR% --war %JENKINS_WAR% --latest false --plugin-download-directory plugins --plugin-file plugins.txt

set JENKINS_HOME=.
java -jar %JENKINS_WAR%
```

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 


Step no.5 from above fails:

```
$ java -jar %PLUGIN_MANAGER_JAR% --war %JENKINS_WAR% --latest false --plugin-download-directory plugins --plugin-file plugins.txt
Provider "jar" not found
```
This command throws the error: `Provider "jar" not found`

When I run it individually this way: 

`$ java -jar jenkins-plugin-manager-2.12.9.jar --war jenkins-2.361.4.war --latest false --plugin-download-directory plugins --plugin-file plugins.txt`

I get:

```
Unable to open jenkins-2.361.4.war

Unable to get Jenkins version from the WAR file jenkins-2.361.4.war

Provider "jar" not found
```

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

The good news is I tried again and it worked. 

It is stuck asking me to paste the password. I do not know where to paste the password. I know what the password is.



Here are the logs:

```
D:\open-source>java -jar ..\jenkins-2.361.4.war
Running from: D:\jenkins-2.361.4.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-11-18 15:16:10.837+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2022-11-18 15:16:10.880+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-11-18 15:16:10.954+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-10.0.11; built: 2022-06-21T21:12:44.640Z; git: d988aa016e0bb2de6fba84c1659049c72eae3e32; jvm 11.0.17+10-LTS-269
2022-11-18 15:16:12.540+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-11-18 15:16:12.604+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: Session workerName=node0
2022-11-18 15:16:13.086+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: D:\open-source\. found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-11-18 15:16:13.218+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@15723761{Jenkins v2.361.4,/,file:///D:/open-source/war/,AVAILABLE}{D:\open-source\.\war}
2022-11-18 15:16:13.238+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@6f45df59{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-11-18 15:16:13.260+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started Server@1356d4d4{STARTING}[10.0.11,sto=0] @3408ms
2022-11-18 15:16:13.262+0000 [id=26]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2022-11-18 15:16:13.542+0000 [id=33]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2022-11-18 15:16:15.324+0000 [id=40]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2022-11-18 15:16:16.956+0000 [id=37]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2022-11-18 15:16:16.970+0000 [id=46]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2022-11-18 15:16:16.972+0000 [id=38]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2022-11-18 15:16:17.306+0000 [id=37]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2022-11-18 15:16:17.307+0000 [id=43]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2022-11-18 15:16:17.308+0000 [id=43]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2022-11-18 15:16:17.319+0000 [id=38]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2022-11-18 15:16:17.337+0000 [id=59]    INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
2022-11-18 15:16:17.344+0000 [id=59]    INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 5 ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/D:/open-source/war/WEB-INF/lib/groovy-all-2.4.21.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-11-18 15:16:17.458+0000 [id=39]    INFO    jenkins.install.SetupWizard#init:

*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

7343d87409b146e39224753de975b611

This may also be found at: D:\open-source\secrets\initialAdminPassword

*************************************************************
*************************************************************
*************************************************************

2022-11-18 15:16:28.998+0000 [id=34]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2022-11-18 15:16:29.028+0000 [id=25]    INFO    hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
```

The cursor just blinks with no prompt to paste the password. 

Something like in the screenshot.

image

**Comment by MarkEWaite** [comment]
> It is stuck asking me to paste the password. I do not know where to paste the password. I know what the password is.

I'm glad it worked.  Open your web browser to http://localhost:8080 and then you can configure Jenkins from inside your web browser. https://www.jenkins.io/doc/tutorials/#tools provides tutorials that can guide your experimenting as well

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

It worked. I am installing the recommended plugins. 

What is the next step?

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Step 3 to recreate the issue is: `Enter the repository URL`.

Which URL does it mean? And where shall I add it?

I have completed the first two steps. Attaching a screenshot.

image

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

You are right. It fails for me too.

Does this mean the issue is not resolved yet? 

The testing stops here?

**Comment by MarkEWaite** [comment]
> Hey @MarkEWaite
> 
> You are right. It fails for me too.
> 
> Does this mean the issue is not resolved yet?
> 
> The testing stops here?

Thanks for confirming it!  Yes, the testing is done.  I'll need to switch into a debugger to understand why the case that we're testing still fails.  The code changes seem reasonable to me, but there may be something missing in order to complete the fix of the issue.

**Comment by Jagrutiti** [comment]
>The code changes seem reasonable to me, but there may be something missing in order to complete the fix of the issue.

I cannot help you with anything as of now?

**Comment by Jagrutiti** [comment]
Do you think I can document the steps? The Windows script you shared with me? If it isn't documented yet?

**Comment by MarkEWaite** [comment]
> Do you think I can document the steps? The Windows script you shared with me? If it isn't documented yet?

That would be a nice addition to add as a comment in 

* https://github.com/jenkinsci/git-plugin/pull/1305

**Comment by Jagrutiti** [comment]
Hey @MarkEWaite 

Let me know anything else I can assist you with :)

To sum up what I did,

The script that you shared was to install Jenkins on my local machine? 

Then I recreated the issue. Right?

**Comment by MarkEWaite** [comment]
> The script that you shared was to install Jenkins on my local machine?
> 
> Then I recreated the issue. Right?

Yes, though I'd describe it a little differently.  You helped me evaluate a pull request by performing interactive testing of the original issue that the pull request is trying to resolve.  In order to help me evaluate that pull request, you installed Jenkins, configured a test job, and observed the results of the test job.  You compared behavior with lightweight checkout with the behavior without lightweight checkout.  That provided some insights into a portion of the many different ways that Jenkins is used.

**Comment by Jagrutiti** [comment]
> You compared behavior with lightweight checkout with the behavior without lightweight checkout

I did not stand the meaning of the jargon `lightweight checkout`.

Thank you for giving me an opportunity to assist you.

I created a build a pipeline myself for the first time last night. I see Jenkins at work every day but never got this clarity until yesterday.

**Comment by MartinKosicky** [comment]
Just to clarify, the lightweight checkout is "testable" only if you can use https://github.com/jenkinsci/workflow-cps-plugin/pull/577 . It was currently drafted because it was afaited for the git plugin (there seems to be some cyclic dependency between the plugins mainly in tests). If you want to test the entire flow, I can undraft that PR https://github.com/jenkinsci/workflow-cps-plugin/pull/577  and can use incremental build to test the lightweight checkout. (Actually that is how we use it in production)

**Comment by MarkEWaite** [comment]
@Jagrutiti I am sincerely sorry, but I don't expect to have time to implement these tests in the next 1-2 months.  I'm closing this pull request.  We can decide to reopen it or create it anew in the future.

**Pull request closed without merging**
